services:
  mongodb:
    image: mongo:8.0
    volumes:
      - ./database:/data/db
    restart: always

  server:
    build: ./backend
    image: echo-server:1.6.0
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env

  nginx:
    build: ./frontend
    image: echo-nginx:1.6.0
    restart: always
    ports:
      - 3100:80
