version: "3.7"

services:
  mongodb:
    image: mongo:5.0
    volumes:
      - ./database:/data/db
    restart: always

  server:
    build: ./backend
    restart: always
    depends_on:
      - mongodb

  nginx:
    build: ./frontend
    restart: always
    ports:
      - 3200:80
